blank_issues_enabled: false
contact_links:
  - name: 🚀 GitHub Community
    url: https://github.com/orgs/Atrophaneura/discussions
    about: Please ask and answer questions here.
  - name: 📬 Matrix
    url: https://matrix.to/#/#Atrophaneura:matrix.org
    about: Chat on matrix.
